//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AupRename.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AupRename.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AviUtl Project Files (*.aup)|*.aup|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_AupFilter {
            get {
                return ResourceManager.GetString("Dialog_AupFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select an AviUtl project file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_AupTitle {
            get {
                return ResourceManager.GetString("Dialog_AupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Programs (*.exe)|*.exe|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_EditorFilter {
            get {
                return ResourceManager.GetString("Dialog_EditorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a text editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_EditorTitle {
            get {
                return ResourceManager.GetString("Dialog_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot write to list.txt .
        ///If it is already open in a text editor, please close it and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CannotWriteListTxt {
            get {
                return ResourceManager.GetString("Error_CannotWriteListTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while loading the AviUtl project file.
        ///The file may be corrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CorruptedAviUtlProjectFile {
            get {
                return ResourceManager.GetString("Error_CorruptedAviUtlProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text editor not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_EditorNotFound {
            get {
                return ResourceManager.GetString("Error_EditorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify a text editor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_EditorNotSelected {
            get {
                return ResourceManager.GetString("Error_EditorNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Editing data not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ExEditNotFound {
            get {
                return ResourceManager.GetString("Error_ExEditNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name on line {0} is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_FileNameTooLong {
            get {
                return ResourceManager.GetString("Error_FileNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   list.txt was not found.
        ///Please start over using New Edit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ListTxtNotFound {
            get {
                return ResourceManager.GetString("Error_ListTxtNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write the error log. :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LogWriteFailed {
            get {
                return ResourceManager.GetString("Error_LogWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file is currently open.
        ///Start a new edit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_NoFileOpen {
            get {
                return ResourceManager.GetString("Error_NoFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not an AviUtl project file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_NotAviUtlProjectFile {
            get {
                return ResourceManager.GetString("Error_NotAviUtlProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too few file names.
        ///Do not remove lines from list.txt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TooFewFilenames {
            get {
                return ResourceManager.GetString("Error_TooFewFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many file names.
        ///Do not add extra lines to list.txt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TooManyFilenames {
            get {
                return ResourceManager.GetString("Error_TooManyFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_WriteFailed {
            get {
                return ResourceManager.GetString("Error_WriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_AupButton {
            get {
                return ResourceManager.GetString("MainWindow_AupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AviUtl Project file (.aup) (Backup recommended) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_AupHeader {
            get {
                return ResourceManager.GetString("MainWindow_AupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_AupPath {
            get {
                return ResourceManager.GetString("MainWindow_AupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ButtonApply {
            get {
                return ResourceManager.GetString("MainWindow_ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ButtonNewEdit {
            get {
                return ResourceManager.GetString("MainWindow_ButtonNewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ButtonReEdit {
            get {
                return ResourceManager.GetString("MainWindow_ButtonReEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ButtonRevert {
            get {
                return ResourceManager.GetString("MainWindow_ButtonRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_EditorButton {
            get {
                return ResourceManager.GetString("MainWindow_EditorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_EditorHeader {
            get {
                return ResourceManager.GetString("MainWindow_EditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_EditorPath {
            get {
                return ResourceManager.GetString("MainWindow_EditorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableAudio {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableBorder {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displacement map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableDisplacement {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graphic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableFigure {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableImage {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synthesis image file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableImageComposition {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableImageComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableMask {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub-filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnablePartialFilter {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnablePartialFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PSDToolKit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnablePsdToolKit {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnablePsdToolKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableScript {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableShadow {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableVideo {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video files synthesis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableVideoComposition {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableVideoComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio waveform display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterEnableWaveform {
            get {
                return ResourceManager.GetString("MainWindow_FilterEnableWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_FilterHeader {
            get {
                return ResourceManager.GetString("MainWindow_FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About AupRename(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Apply {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Edit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Edit(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_NewEdit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_NewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Open {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View on GitHub(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_OpenUrl {
            get {
                return ResourceManager.GetString("MainWindow_Menu_OpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Quit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Edit(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_ReEdit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_ReEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Menu_Revert {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no files to edit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NoFilesToEdit {
            get {
                return ResourceManager.GetString("Message_NoFilesToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes have been applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_RenameCompleted {
            get {
                return ResourceManager.GetString("Message_RenameCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes have been reverted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_RevertCompleted {
            get {
                return ResourceManager.GetString("Message_RevertCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editing {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_OpenEditor {
            get {
                return ResourceManager.GetString("Status_OpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes applied to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_RenameCompleted {
            get {
                return ResourceManager.GetString("Status_RenameCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverted changes to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_RevertCompleted {
            get {
                return ResourceManager.GetString("Status_RevertCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About AupRename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionWindow_Title {
            get {
                return ResourceManager.GetString("VersionWindow_Title", resourceCulture);
            }
        }
    }
}
